export const ghanadata = [
    {
        id: 1,
        region_name: 'Ashanti',
        districts: [
            { district_name: 'Adansi North District' },
            { district_name: 'Adansi South District' },
            { district_name: 'Afigya Kwabre District' },
            { district_name: 'Ahafo Ano North Municipal' },
            { district_name: 'Ahafo Ano South West District' },
            { district_name: 'Amansie Central District' },
            { district_name: 'Amansie West District' },
            { district_name: 'Asante Akim Central Municipal' },
            { district_name: 'Asante Akim North District' },
            { district_name: 'Asante Akim South Municipal' },
            { district_name: 'Asokore Mampong Municipal' },
            { district_name: 'Atwima Kwanwoma District' },
            { district_name: 'Atwima Mponua District' },
            { district_name: 'Atwima Nwabiagya Municipal' },
            { district_name: 'Bekwai Municipal' },
            { district_name: 'Bosome Freho District' },
            { district_name: 'Bosomtwe District' },
            { district_name: 'Ejisu Municipal' },
            { district_name: 'Ejura Sekyedumase Municipal' },
            { district_name: 'Kumasi Metropolitan' },
            { district_name: 'Kwabre East Municipal' },
            { district_name: 'Mampong Municipal' },
            { district_name: 'Obuasi Municipal' },
            { district_name: 'Offinso Municipal' },
            { district_name: 'Sekyere Afram Plains District' },
            { district_name: 'Sekyere Central District' },
            { district_name: 'Sekyere East District' },
            { district_name: 'Sekyere Kumawu District' },
            { district_name: 'Sekyere South District' },
        ]
    },
    {
        id: 2,
        region_name: 'Ahafo',
        districts: [
            { district_name: 'Asunafo North Municipal' },
            { district_name: 'Asunafo South District' },
            { district_name: 'Asutifi North District' },
            { district_name: 'Asutifi South District' },
            { district_name: 'Tano North Municipal' },
            { district_name: 'Tano South Municipal' }
        ]
    },
    {
        id: 3,
        region_name: 'Bono East',
        districts: [
            { district_name: 'Atebubu-Amantin District' },
            { district_name: 'Kintampo North Municipal' },
            { district_name: 'Kintampo South District' },
            { district_name: 'Nkoranza North District' },
            { district_name: 'Nkoranza South Municipal' },
            { district_name: 'Pru District' },
            { district_name: 'Sene East District' },
            { district_name: 'Sene West District' },
            { district_name: 'Techiman Municipal' },
            { district_name: 'Techiman North District' },
        ]
    },
    {
        id: 4,
        region_name: 'Bono',
        districts: [
            { district_name: 'Banda District' },
            { district_name: 'Berekum East Municipal' },
            { district_name: 'Berekum West District' },
            { district_name: 'Dormaa Central Municipal' },
            { district_name: 'Dormaa East District' },
            { district_name: 'Dormaa West District' },
            { district_name: 'Jaman North District' },
            { district_name: 'Jaman South Municipal' },
            { district_name: 'Sunyani Municipal' },
            { district_name: 'Sunyani West District' },
            { district_name: 'Tain District' },
            { district_name: 'Wenchi Municipal' },
        ]
    },
    {
        id: 5,
        region_name: 'Central',
        districts: [
            { district_name: 'Abura/Asebu/Kwamankese District' },
            { district_name: 'Agona East District' },
            { district_name: 'Agona West Municipal' },
            { district_name: 'Ajumako/Enyan/Essiam District' },
            { district_name: 'Asikuma/Odoben/Brakwa District' },
            { district_name: 'Assin Fosu Municipal' },
            { district_name: 'Assin North Municipal' },
            { district_name: 'Assin South District' },
            { district_name: 'Awutu Senya East Municipal' },
            { district_name: 'Awutu Senya West District' },
            { district_name: 'Cape Coast Metropolitan' },
            { district_name: 'Effutu Municipal' },
            { district_name: 'Ekumfi District' },
            { district_name: 'Gomoa East District' },
            { district_name: 'Gomoa West District' },
            { district_name: 'Komenda/Edina/Eguafo/Abirem Municipal' },
            { district_name: 'Mfantsiman Municipal' },
            { district_name: 'Twifo-Ati Morkwa District' },
            { district_name: 'Twifo-Hemang-Lower Denkyira District' },
            { district_name: 'Upper Denkyira East Municipal' },
            { district_name: 'Upper Denkyira West District' },
        ]
    },
    {
        id: 6,
        region_name: 'Eastern',
        districts: [
            { district_name: 'Akuapim North Municipal' },
            { district_name: 'Akuapim South District' },
            { district_name: 'Akyemansa District' },
            { district_name: 'Asene/Manso/Akroso District' },
            { district_name: 'Asuogyaman District' },
            { district_name: 'Atiwa District' },
            { district_name: 'Ayensuano District' },
            { district_name: 'Birim Central Municipal' },
            { district_name: 'Birim North District' },
            { district_name: 'Birim South District' },
            { district_name: 'Denkyembour District' },
            { district_name: 'Fanteakwa District' },
            { district_name: 'Kwaebibirem District' },
            { district_name: 'Kwahu Afram Plains North District' },
            { district_name: 'Kwahu Afram Plains South District' },
            { district_name: 'Kwahu East District' },
            { district_name: 'Kwahu South District' },
            { district_name: 'Kwahu West Municipal' },
            { district_name: 'Lower Manya Krobo Municipal' },
            { district_name: 'New Juaben Municipal' },
            { district_name: 'Nsawam Adoagyiri Municipal' },
            { district_name: 'Suhum Municipal' },
            { district_name: 'Upper Manya Krobo District' },
            { district_name: 'Upper West Akim District' },
            { district_name: 'West Akim Municipal' },
            { district_name: 'Yilo Krobo Municipal' },
        ]
    },
    {
        id: 7,
        region_name: 'Greater Accra',
        districts: [
            { district_name: 'Ablekuma Central Municipal' },
            { district_name: 'Ablekuma North Municipal' },
            { district_name: 'Ablekuma West Municipal' },
            { district_name: 'Accra Metropolitan' },
            { district_name: 'Ada East District' },
            { district_name: 'Ada West District' },
            { district_name: 'Adentan Municipal' },
            { district_name: 'Ashaiman Municipal' },
            { district_name: 'Ayawaso Central Municipal' },
            { district_name: 'Ayawaso East Municipal' },
            { district_name: 'Ayawaso North Municipal' },
            { district_name: 'Ayawaso West Municipal' },
            { district_name: 'Ga Central Municipal' },
            { district_name: 'Ga East Municipal' },
            { district_name: 'Ga North Municipal' },
            { district_name: 'Ga South Municipal' },
            { district_name: 'Ga West Municipal' },
            { district_name: 'Kpone Katamanso District' },
            { district_name: 'Korle Klottey Municipal' },
            { district_name: 'La Dade Kotopon Municipal' },
            { district_name: 'La Nkwantanang Madina Municipal' },
            { district_name: 'Ledzokuku Municipal' },
            { district_name: 'Ningo Prampram District' },
            { district_name: 'Okaikwei North Municipal' },
            { district_name: 'Shai-Osudoku District' },
            { district_name: 'Tema Metropolitan' },
            { district_name: 'Tema West Municipal' },
            { district_name: 'Weija Gbawe Municipal' },
        ]
    },
    {
        id: 8,
        region_name: 'Savannah',
        districts: [
            { district_name: 'Bole District' },
            { district_name: 'Central Gonja District' },
            { district_name: 'East Gonja District' },
            { district_name: 'North East Gonja District' },
            { district_name: 'North Gonja District' },
            { district_name: 'Sawla-Tuna-Kalba District' },
            { district_name: 'West Gonja District' },
        ],
    },
    {
        id: 9,
        region_name: 'North East',
        districts: [
            { district_name: 'Bunkpurugu-Nyakpanduri District' },
            { district_name: 'Chereponi District' },
            { district_name: 'East Mamprusi Municipal' },
            { district_name: 'Mamprugu Moagduri District' },
            { district_name: 'West Mamprusi Municipal' },
            { district_name: 'Yunyoo-Nasuan District' },
        ]
    },
    {
        id: 10,
        region_name: 'Northern',
        districts: [
            { district_name: 'Gushegu Municipal' },
            { district_name: 'Karaga District' },
            { district_name: 'Kpandai District' },
            { district_name: 'Kumbungu District' },
            { district_name: 'Mion District' },
            { district_name: 'Nanton District' },
            { district_name: 'Nanumba North Municipal' },
            { district_name: 'Nanumba South District' },
            { district_name: 'Saboba District' },
            { district_name: 'Sagnarigu Municipal' },
            { district_name: 'Savelugu Municipal' },
            { district_name: 'Tatale-Sanguli District' },
            { district_name: 'Tolon District' },
            { district_name: 'Yendi Municipal' },
            { district_name: 'Zabzugu District' },
        ]
    },
    {
        id: 11,
        region_name: 'Upper East',
        districts: [
            { district_name: 'Bawku Municipal' },
            { district_name: 'Bawku West District' },
            { district_name: 'Binduri District' },
            { district_name: 'Bolgatanga Municipal' },
            { district_name: 'Bongo District' },
            { district_name: 'Garu District' },
            { district_name: 'Kassena Nankana Municipal' },
            { district_name: 'Kassena Nankana West District' },
            { district_name: 'Nabdam District' },
            { district_name: 'Pusiga District' },
            { district_name: 'Talensi District' },
            { district_name: 'Tempane District' },
        ]
    },
    {
        id: 12,
        region_name: 'Upper West',
        districts: [
            { district_name: 'Daffiama Bussie Issa District' },
            { district_name: 'Jirapa Municipal' },
            { district_name: 'Lambussie District' },
            { district_name: 'Lawra Municipal' },
            { district_name: 'Nadowli-Kaleo District' },
            { district_name: 'Nandom Municipal' },
            { district_name: 'Sissala East Municipal' },
            { district_name: 'Sissala West District' },
            { district_name: 'Wa East District' },
            { district_name: 'Wa Municipal' },
            { district_name: 'Wa West District' },
        ]
    },
    {
        id: 13,
        region_name: 'Volta',
        districts: [
            { district_name: 'Adaklu District' },
            { district_name: 'Afadzato South District' },
            { district_name: 'Agotime Ziope District' },
            { district_name: 'Akatsi North District' },
            { district_name: 'Akatsi South District' },
            { district_name: 'Central Tongu District' },
            { district_name: 'Ho Municipal' },
            { district_name: 'Ho West District' },
            { district_name: 'Hohoe Municipal' },
            { district_name: 'Keta Municipal' },
            { district_name: 'Ketu North Municipal' },
            { district_name: 'Ketu South Municipal' },
            { district_name: 'Kpando Municipal' },
            { district_name: 'North Dayi District' },
            { district_name: 'North Tongu District' },
            { district_name: 'South Dayi District' },
            { district_name: 'South Tongu District' },
        ]
    },
    {
        id: 14,
        region_name: 'Oti',
        districts: [
            { district_name: 'Biakoye District' },
            { district_name: 'Jasikan District' },
            { district_name: 'Kadjebi District' },
            { district_name: 'Krachi East Municipal' },
            { district_name: 'Krachi Nchumuru District' },
            { district_name: 'Krachi West District' },
            { district_name: 'Nkwanta North District' },
            { district_name: 'Nkwanta South Municipal' },
        ]
    },
    {
        id: 15,
        region_name: 'Western',
        districts: [
            { district_name: 'Ahanta West Municipal' },
            { district_name: 'Effia-Kwesimintsim Municipal' },
            { district_name: 'Ellembelle District' },
            { district_name: 'Jomoro Municipal' },
            { district_name: 'Mpohor District' },
            { district_name: 'Nzema East Municipal' },
            { district_name: 'Prestea-Huni Valley Municipal' },
            { district_name: 'Sekondi-Takoradi Metropolitan' },
            { district_name: 'Shama District' },
            { district_name: 'Tarkwa-Nsuaem Municipal' },
            { district_name: 'Wassa Amenfi Central District' },
            { district_name: 'Wassa Amenfi East Municipal' },
            { district_name: 'Wassa Amenfi West Municipal' },
            { district_name: 'Wassa East District' },
        ]
    },
    {
        id: 16,
        region_name: 'Western North',
        districts: [
            { district_name: 'Aowin Municipal' },
            { district_name: 'Bia East District' },
            { district_name: 'Bia West District' },
            { district_name: 'Bibiani-Anhwiaso-Bekwai Municipal' },
            { district_name: 'Juaboso District' },
            { district_name: 'Sefwi-Akontombra District' },
            { district_name: 'Sefwi-Bodi District' },
            { district_name: 'Sefwi-Wiawso Municipal' },
            { district_name: 'Suaman District' },
        ]
    }
];
   